-- CREATE DATABASE Banco_CL
--     DEFAULT CHARACTER SET = 'utf8mb4';

USE Banco_CL;

DROP TABLE IF EXISTS tipo_cliente;
DROP TABLE IF EXISTS tipo_cuenta;
DROP TABLE IF EXISTS tipo_tarjetas;
DROP TABLE IF EXISTS marca_tarjeta;
DROP TABLE IF EXISTS nivel_tarjeta;
DROP TABLE IF EXISTS tipo_prestamo;



CREATE TABLE IF NOT EXISTS tipo_cliente (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tipo ENUM('REGULAR', 'ESTANDAR', 'PREFERENCIAL', 'VIP') NOT NULL,
    descripcion VARCHAR(120) NOT NULL
);


CREATE TABLE IF NOT EXISTS tipo_cuenta (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tipo ENUM('AHORROS', 'CORRIENTE', 'NOMINA', 'PLAZO FIJO', 'JUVENIL', 'EMPRESARIAL', 'DIVISA EXTRANJERA', 'DIGITAL') NOT NULL,
    descripcion VARCHAR(120) NOT NULL
);


CREATE TABLE IF NOT EXISTS tipo_tarjetas(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tipo ENUM('DEBITO', 'CREDITO', 'PREPAGO', 'EMPRESARIALES', 'NOMINA', 'VIRTUALES') NOT NULL,
    descripcion VARCHAR(120) NOT NULL
);



CREATE TABLE IF NOT EXISTS marca_tarjeta (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre ENUM('VISA', 'MASTERCARD', 'AMERICAN EXPRESS', 'DINERS CLUB', 'DISCOVER', 'UNION PAY', 'SERVIBANCA', 'CREDIBANCO') NOT NULL,
    descripcion VARCHAR(120) NOT NULL
);



CREATE TABLE IF NOT EXISTS nivel_tarjeta (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nivel ENUM('CLASICA', 'GOLD', 'PLATINO', 'BLACK', 'SIGNATURE', 'INFINITE', 'EMPRESARIAL') NOT NULL,
    descripcion VARCHAR(120) NOT NULL
);




CREATE TABLE IF NOT EXISTS tipo_prestamo (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tipo ENUM('PERSONAL', 'HIPOTECARIO', 'AUTOMOTRIZ', 'ESTUDIANTIL', 'LINEA DE CREDITO', 'COMERCIAL', 'LIBRE INVERSION', 'CREDITO ROTATIVO', 'PRENDARIO') NOT NULL,
    descripcion VARCHAR(120) NOT NULL
);
