-- CREATE DATABASE Banco_CL
--     DEFAULT CHARACTER SET = 'utf8mb4';

USE Banco_CL;



DROP TABLE IF EXISTS prestamos;
DROP TABLE IF EXISTS tarjetas_bancarias;
DROP TABLE IF EXISTS metodos_de_pago_cuenta;
DROP TABLE IF EXISTS cuenta;
DROP TABLE IF EXISTS interes;
DROP TABLE IF EXISTS monedas;
DROP TABLE IF EXISTS metodos_de_pago;
DROP TABLE IF EXISTS clientes;
DROP TABLE IF EXISTS tipo_nit;
DROP TABLE IF EXISTS descuento;
DROP TABLE IF EXISTS tipo_cuota_de_manejo;
DROP TABLE IF EXISTS tipo_prestamo;
DROP TABLE IF EXISTS nivel_tarjeta;
DROP TABLE IF EXISTS marca_tarjeta;
DROP TABLE IF EXISTS tipo_tarjetas;
DROP TABLE IF EXISTS tipo_cuenta;
DROP TABLE IF EXISTS tipo_cliente;




CREATE TABLE IF NOT EXISTS tipo_cliente (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tipo ENUM('REGULAR', 'ESTANDAR', 'PREFERENCIAL', 'VIP') NOT NULL,
    descripcion VARCHAR(120) NOT NULL
);


CREATE TABLE IF NOT EXISTS tipo_cuenta (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tipo ENUM('AHORROS', 'CORRIENTE', 'NOMINA', 'PLAZO FIJO', 'JUVENIL', 'EMPRESARIAL', 'DIVISA EXTRANJERA', 'DIGITAL') NOT NULL,
    descripcion VARCHAR(120) NOT NULL
);


CREATE TABLE IF NOT EXISTS tipo_tarjetas(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tipo ENUM('DEBITO', 'CREDITO', 'PREPAGO', 'EMPRESARIALES', 'NOMINA', 'VIRTUALES') NOT NULL,
    descripcion VARCHAR(120) NOT NULL
);



CREATE TABLE IF NOT EXISTS marca_tarjeta (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre ENUM('VISA', 'MASTERCARD', 'AMERICAN EXPRESS', 'DINERS CLUB', 'DISCOVER', 'UNION PAY', 'SERVIBANCA', 'CREDIBANCO') NOT NULL,
    descripcion VARCHAR(120) NOT NULL
);



CREATE TABLE IF NOT EXISTS nivel_tarjeta (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nivel ENUM('CLASICA', 'GOLD', 'PLATINO', 'BLACK', 'SIGNATURE', 'INFINITE', 'EMPRESARIAL') NOT NULL,
    descripcion VARCHAR(120) NOT NULL
);




CREATE TABLE IF NOT EXISTS tipo_prestamo (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tipo ENUM('PERSONAL', 'HIPOTECARIO', 'AUTOMOTRIZ', 'ESTUDIANTIL', 'LINEA DE CREDITO', 'COMERCIAL', 'LIBRE INVERSION', 'CREDITO ROTATIVO', 'PRENDARIO') NOT NULL,
    descripcion VARCHAR(120) NOT NULL
);




CREATE TABLE IF NOT EXISTS tipo_cuota_de_manejo (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tipo ENUM('PERIODICA', 'TIPO PRODUCTO', 'PERFIL CLIENTE', 'EXONERADA') NOT NULL,
    descripcion VARCHAR(120) NOT NULL
);


CREATE TABLE IF NOT EXISTS descuento (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tipo ENUM('POR USO', 'DEBITO AUTOMATICO', 'CUOTA MANEJO', 'CONVENIO', 'CASHBACK', 'SEGUROS', 'INTERESES', 'COMPRAS') NOT NULL,
    descripcion VARCHAR(120) NOT NULL,
    valor DECIMAL (15,2),
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL
);




CREATE TABLE IF NOT EXISTS tipo_nit (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre ENUM('GRAN CONTRIBUYENTE','REGIMEN COMUN','REGIMEN SIMPLE','REGIMEN ESPECIAL','REGIMEN SIMPLIFICADO','NO RESPONSABLE DE IVA','RESPONSABLE DE IVA','AUTORRETENEDOR','ENTIDAD EXTRANJERA','SIN CLASIFICAR') NOT NULL,
    descripcion VARCHAR(120) NOT NULL
);

CREATE TABLE IF NOT EXISTS clientes (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    NIT VARCHAR(20) NOT NULL UNIQUE,
    primer_nombre VARCHAR(50),
    segundo_nombre VARCHAR(50),
    primer_apellido VARCHAR(50),
    segundo_apellido VARCHAR(50),
    num_contacto VARCHAR(20) NOT NULL,
    email VARCHAR(40) NOT NULL,
    tipo_persona ENUM('NATURAL', 'JURIDICA') NOT NULL,
    tipo_cliente_id BIGINT NOT NULL,
    tipo_nit_id BIGINT NOT NULL,
    FOREIGN KEY (tipo_cliente_id) REFERENCES tipo_cliente(id) ON DELETE CASCADE,
    FOREIGN KEY (tipo_nit_id) REFERENCES tipo_nit(id) ON DELETE CASCADE
);




CREATE TABLE IF NOT EXISTS metodos_de_pago (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre ENUM('EFECTIVO', 'TRANSFERENCIA BANCARIA', 'DEBITO AUTOMATICO', 'TARJETA CREDITO', 'TARJETA DEBITO', 'CHEQUES', 'BILLETERA DIGITAL', 'PAGO EN LINEA', 'CONSIGNACION', 'DESCUENTO NOMINA', 'PAGO MOVIL', 'CUENTA CORRIENTE', 'CUENTA AHORRO', 'PSE', 'OTRO') NOT NULL,
    descripcion VARCHAR(120) NOT NULL
);


CREATE TABLE IF NOT EXISTS monedas (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre ENUM('COP', 'USD', 'EUR', 'GBP', 'JPY', 'CNY', 'CHF', 'CAD', 'AUD', 'BRL', 'MXN', 'CLP', 'PEN', 'ARS', 'VES', 'INR', 'otros'),
    simbolo ENUM ('$', '€', '£', '¥', 'Fr', 'R$', '₹', 'S/', 'Bs', '$U') NOT NULL,
    descripcion VARCHAR(120) NOT NULL
);




CREATE TABLE IF NOT EXISTS interes (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tipo ENUM ('FIJO', 'VARIABLE', 'MIXTO', 'SIMPLE', 'COMPUESTO', 'NOMINAL', 'EFECTIVO', 'MORA', 'NO APLICA') NOT NULL,
    valor DECIMAL (5,4) NOT NULL
);





CREATE TABLE IF NOT EXISTS cuenta (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    cliente_id BIGINT NOT NULL,
    tipo_cuenta_id BIGINT NOT NULL,
    num VARCHAR(30) NOT NULL UNIQUE,
    saldo_disponible DECIMAL(15,2) NOT NULL DEFAULT 0,
    transacciones_realizadas INT NOT NULL DEFAULT 0,
    estado ENUM('ACTIVA', 'CERRADA', 'BLOQUEADA') NOT NULL,
    monedas_id BIGINT NOT NULL,
    fecha_apertura TIMESTAMP NOT NULL,
    fecha_cierre TIMESTAMP,
    interes_id BIGINT NOT NULL,
    FOREIGN KEY (cliente_id) REFERENCES clientes (id) ON DELETE CASCADE,
    FOREIGN KEY (tipo_cuenta_id) REFERENCES tipo_cuenta (id) ON DELETE CASCADE,
    FOREIGN KEY (monedas_id) REFERENCES monedas (id) ON DELETE CASCADE,
    FOREIGN KEY (interes_id) REFERENCES interes (id) ON DELETE CASCADE
);



CREATE TABLE IF NOT EXISTS metodos_de_pago_cuenta (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    metodos_de_pago_id BIGINT NOT NULL,
    cuenta_id BIGINT NOT NULL,
    FOREIGN KEY (metodos_de_pago_id) REFERENCES metodos_de_pago (id) ON DELETE CASCADE,
    FOREIGN KEY (cuenta_id) REFERENCES cuenta (id) ON DELETE CASCADE
);





CREATE TABLE IF NOT EXISTS tarjetas_bancarias (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    estado ENUM('ACTIVA', 'CERRADA', 'BLOQUEADA') NOT NULL,
    fecha_emision TIMESTAMP NOT NULL,
    fecha_vencimiento TIMESTAMP NOT NULL,
    num VARCHAR(30) NOT NULL UNIQUE,
    codigo_seguridad VARCHAR(4) UNIQUE,
    tipo_tarjetas_id BIGINT NOT NULL,
    marca_tarjeta_id BIGINT NOT NULL,
    nivel_tarjeta_id BIGINT NOT NULL,
    FOREIGN KEY (tipo_tarjetas_id) REFERENCES tipo_tarjetas (id) ON DELETE CASCADE,
    FOREIGN KEY (marca_tarjeta_id) REFERENCES marca_tarjeta (id) ON DELETE CASCADE,
    FOREIGN KEY (nivel_tarjeta_id) REFERENCES nivel_tarjeta (id) ON DELETE CASCADE
);



CREATE TABLE IF NOT EXISTS prestamos (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    cuenta_id BIGINT NOT NULL,
    monto DECIMAL (15,2) NOT NULL,
    interes_id BIGINT NOT NULL,
    fecha_desembolso TIMESTAMP NOT NULL,
    plazo_meses TINYINT(2) NOT NULL,
    frecuencia_pago ENUM('DIARIO','SEMANAL', 'QUINCENAL', 'MENSUAL', 'BIMESTRAL', 'TRIMESTRAL', 'CUATRIMESTRAL', 'SEMESTRAL', 'ANUAL', 'UNICO', 'OTRO') NOT NULL,
    estado ENUM('SOLICITADO', 'EN EVALUACION', 'APROBADO', 'DESEMBOLSADO', 'EN CURSO', 'EN MORA', 'REESTRUCTURADO', 'CASTIGADO', 'PAGADO', 'CANCELADO', 'CERRADO') NOT NULL,
    saldo_restante DECIMAL (15,2) NOT NULL,
    fecha_solicitud TIMESTAMP NOT NULL,
    FOREIGN KEY (interes_id) REFERENCES interes (id) ON DELETE CASCADE,
    FOREIGN KEY (cuenta_id) REFERENCES cuenta (id) ON DELETE CASCADE
);


