CREATE DATABASE Banco_CL
    DEFAULT CHARACTER SET = 'utf8mb4';

USE Banco_CL;

DROP TABLE IF EXISTS tipo_cliente;
CREATE TABLE IF NOT EXISTS tipo_cliente (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tipo ENUM('REGULAR', 'ESTANDAR', 'PREFERENCIAL', 'VIP') NOT NULL,
    descripcion VARCHAR(120) NOT NULL
);


DROP TABLE IF EXISTS tipo_cuenta;
CREATE TABLE IF NOT EXISTS tipo_cuenta (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tipo ENUM('AHORROS', 'CORRIENTE', 'NOMINA', 'PLAZO FIJO', 'JUVENIL', 'EMPRESARIAL', 'DIVISA EXTRANJERA', 'DIGITAL') NOT NULL,
    descripcion VARCHAR(120)
);